# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIloads.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(244, 75)
        Form.setMinimumSize(QtCore.QSize(244, 75))
        Form.setMaximumSize(QtCore.QSize(244, 75))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.img = QtWidgets.QLabel(Form)
        self.img.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.img.setObjectName("img")
        self.wait = QtWidgets.QLabel(Form)
        self.wait.setGeometry(QtCore.QRect(70, 10, 161, 51))
        self.wait.setObjectName("wait")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Loading core"))
        self.img.setText(_translate("Form", "<html><head/><body><p><img src=\":/source/clocks.png\" width=\"50\" height=\"50\"/></p></body></html>"))
        self.wait.setText(_translate("Form", "Please, wait..."))
import Gamecore.source_rc
